#
# Automagically generated by Approximatrix Simply Fortran 2.41
#
FC="gfortran"
CC="gcc"
AR="ar"
WRC="windres"
RM=rm -f

IDIR=-I"/Applications/Simply Fortran.app/Contents/Resources/gcc/include/" 

LDIR=-L"/Applications/Simply Fortran.app/Contents/Resources/gcc/lib/" 


OPTFLAGS= -g

SPECIALFLAGS=$(IDIR)

RCFLAGS=-O coff

PRJ_FFLAGS=

PRJ_CFLAGS=

PRJ_LFLAGS=

FFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_FFLAGS) -Jmodules 

CFLAGS=$(SPECIALFLAGS) $(OPTFLAGS) $(PRJ_CFLAGS)

"build/error.o": "src/error.f90" "modules/moddatatypes.mod" "modules/prmflow.mod"
	@echo Compiling src/error.f90
	@$(FC) -c -o "build/error.o" $(FFLAGS) "src/error.f90"

"build/flux.o": "src/flux.f90" "modules/moddatatypes.mod"
	@echo Compiling src/flux.f90
	@$(FC) -c -o "build/flux.o" $(FFLAGS) "src/flux.f90"

"build/initialCond.o": "src/initialCond.f90" "modules/moddatatypes.mod" "modules/prmflow.mod"
	@echo Compiling src/initialCond.f90
	@$(FC) -c -o "build/initialCond.o" $(FFLAGS) "src/initialCond.f90"

"build/main.o": "src/main.f90" "modules/moddatatypes.mod" "modules/prmflow.mod"
	@echo Compiling src/main.f90
	@$(FC) -c -o "build/main.o" $(FFLAGS) "src/main.f90"

"build/minmod.o": "src/minmod.f90" "modules/moddatatypes.mod"
	@echo Compiling src/minmod.f90
	@$(FC) -c -o "build/minmod.o" $(FFLAGS) "src/minmod.f90"

"build/mp5.o": "src/mp5.f90" "modules/moddatatypes.mod"
	@echo Compiling src/mp5.f90
	@$(FC) -c -o "build/mp5.o" $(FFLAGS) "src/mp5.f90"

"build/muscl.o": "src/muscl.f90" "modules/moddatatypes.mod"
	@echo Compiling src/muscl.f90
	@$(FC) -c -o "build/muscl.o" $(FFLAGS) "src/muscl.f90"

"build/output.o": "src/output.f90" "modules/moddatatypes.mod" "modules/prmflow.mod"
	@echo Compiling src/output.f90
	@$(FC) -c -o "build/output.o" $(FFLAGS) "src/output.f90"

"build/prmflow.o": "src/prmflow.f90"
	@echo Compiling src/prmflow.f90
	@$(FC) -c -o "build/prmflow.o" $(FFLAGS) "src/prmflow.f90"
"modules/moddatatypes.mod" "modules/prmflow.mod" : "build/prmflow.o" .EXISTSONLY
	@echo Compiling src/prmflow.f90
	@$(FC) -c -o "build/prmflow.o" $(FFLAGS) "src/prmflow.f90"

"build/reconstruction.o": "src/reconstruction.f90" "modules/moddatatypes.mod" "modules/prmflow.mod"
	@echo Compiling src/reconstruction.f90
	@$(FC) -c -o "build/reconstruction.o" $(FFLAGS) "src/reconstruction.f90"

"build/residual.o": "src/residual.f90" "modules/moddatatypes.mod" "modules/prmflow.mod"
	@echo Compiling src/residual.f90
	@$(FC) -c -o "build/residual.o" $(FFLAGS) "src/residual.f90"

"build/solrange.o": "src/solrange.f90" "modules/moddatatypes.mod" "modules/prmflow.mod"
	@echo Compiling src/solrange.f90
	@$(FC) -c -o "build/solrange.o" $(FFLAGS) "src/solrange.f90"

"build/tvd.o": "src/tvd.f90" "modules/moddatatypes.mod"
	@echo Compiling src/tvd.f90
	@$(FC) -c -o "build/tvd.o" $(FFLAGS) "src/tvd.f90"

"build/updSolution.o": "src/updSolution.f90" "modules/moddatatypes.mod" "modules/prmflow.mod"
	@echo Compiling src/updSolution.f90
	@$(FC) -c -o "build/updSolution.o" $(FFLAGS) "src/updSolution.f90"

"build/wavespeed.o": "src/wavespeed.f90" "modules/moddatatypes.mod"
	@echo Compiling src/wavespeed.f90
	@$(FC) -c -o "build/wavespeed.o" $(FFLAGS) "src/wavespeed.f90"

"build/weno3.o": "src/weno3.f90" "modules/moddatatypes.mod"
	@echo Compiling src/weno3.f90
	@$(FC) -c -o "build/weno3.o" $(FFLAGS) "src/weno3.f90"

"build/weno5.o": "src/weno5.f90" "modules/moddatatypes.mod"
	@echo Compiling src/weno5.f90
	@$(FC) -c -o "build/weno5.o" $(FFLAGS) "src/weno5.f90"

clean: .SYMBOLIC
	@echo Deleting build/error.o and related files
	@$(RM) "build/error.o"
	@echo Deleting build/flux.o and related files
	@$(RM) "build/flux.o"
	@echo Deleting build/initialCond.o and related files
	@$(RM) "build/initialCond.o"
	@echo Deleting build/main.o and related files
	@$(RM) "build/main.o"
	@echo Deleting build/minmod.o and related files
	@$(RM) "build/minmod.o"
	@echo Deleting build/mp5.o and related files
	@$(RM) "build/mp5.o"
	@echo Deleting build/muscl.o and related files
	@$(RM) "build/muscl.o"
	@echo Deleting build/output.o and related files
	@$(RM) "build/output.o"
	@echo Deleting build/prmflow.o and related files
	@$(RM) "build/prmflow.o" "modules/moddatatypes.mod" "modules/moddatatypes.smod" "modules/prmflow.mod" "modules/prmflow.smod"
	@echo Deleting build/reconstruction.o and related files
	@$(RM) "build/reconstruction.o"
	@echo Deleting build/residual.o and related files
	@$(RM) "build/residual.o"
	@echo Deleting build/solrange.o and related files
	@$(RM) "build/solrange.o"
	@echo Deleting build/tvd.o and related files
	@$(RM) "build/tvd.o"
	@echo Deleting build/updSolution.o and related files
	@$(RM) "build/updSolution.o"
	@echo Deleting build/wavespeed.o and related files
	@$(RM) "build/wavespeed.o"
	@echo Deleting build/weno3.o and related files
	@$(RM) "build/weno3.o"
	@echo Deleting build/weno5.o and related files
	@$(RM) "build/weno5.o"
	@echo Deleting target
	@$(RM) "target"

"target":  "build/error.o" "build/flux.o" "build/initialCond.o" "build/main.o" "build/minmod.o" "build/mp5.o" "build/muscl.o" "build/output.o" "build/prmflow.o" "build/reconstruction.o" "build/residual.o" "build/solrange.o" "build/tvd.o" "build/updSolution.o" "build/wavespeed.o" "build/weno3.o" "build/weno5.o" "build/main.prj.target"
	@echo Generating target
	@$(FC) -o "target" -static-libgfortran -static-libgcc -static-libstdc++ "build/error.o" "build/flux.o" "build/initialCond.o" "build/main.o" "build/minmod.o" "build/mp5.o" "build/muscl.o" "build/output.o" "build/prmflow.o" "build/reconstruction.o" "build/residual.o" "build/solrange.o" "build/tvd.o" "build/updSolution.o" "build/wavespeed.o" "build/weno3.o" "build/weno5.o" $(LDIR) $(PRJ_LFLAGS)

all: "target" .SYMBOLIC

